### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by veeenu** [joelnir/SplitNotes#11]
I tried SplitNotes but found out that having only the data for one split available at a time, and it switching suddenly, is a bit confusing (e.g. I may need some info from splits before or after the current). I sketched up a prototype in node/html of a behavior I find more adequate. I apologize for the poor quality, but here's a screencap of it:

https://drive.google.com/file/d/0B5MtLjtexmx8UG1BbjVUdXM1cVk/view

I hope you find this useful!

**Comment by joeloskarsson** [comment]
Are you aware that there already is an option to display notes from the next split as well? Great looking prototype, but I think I personally would not like to have to much animations going on, since it could be distracting from the game.

**Comment by veeenu** [comment]
I should have looked more carefully, I didn't notice the option.

I think animations can be useful to have in the peripheral vision so the brain can anchor to the flow of content, and be more ready to take in the information when it is needed (of course it shouldn't be overdone, 100-300 ms tops, with smooth easings).

I'm going to run some tests both with and without animations anyway -- I've been working on my own version from scratch, to get a bit of practice. If you ever decide to put them in (maybe as an option) I'll be glad to contribute if you want. :)

**Comment by joeloskarsson** [comment]
The problem is that the software is written in python, which doesn't give that many good options when it comes to the graphical interface. I also made SplitNotes as a practice project at first, so therefore it has some design issues. I would like to completely rework the code and maybe even start over from scratch in another language, but I sadly don't have the time at the moment :(

**Comment by veeenu** [comment]
Tkinter is one of the ugliest ui toolkits around, but not totally unworkable :)
But yeah doing it from scratch is always a good idea if you want to practice.
Time is always a problem :D
