### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by linkviii** [joelnir/SplitNotes#13]
Saw someone on twitter mention this. I'm interested in adding features and stuff. No stated license means all rights are reserved, you can look at the code but can't touch it. Also if you're bundling python and tkiner in the release, there is probably some license file that should be accompanying.

**Comment by joeloskarsson** [comment]
Hi, this project was mostly just a hobby thing and I didn't really expect other people to use it, so never bothered to look into licenses and such. Should probably take a look at that now though. 

Feel free to contribute, but I have to warn you that there are some problems with the project that I wish I would have done differently. I've been thinking about rewriting the entire program in some other language and using another graphics library, but haven't had time to start on that. Feel free to get in touch if you want to discuss more.

**Comment by linkviii** [comment]
Well there apparently are people using it! 
I was thinking using markdown for the notes would be cool. Would probably require using a graphic library with a web view or something (markdown is designed to generate html).
Something I plan to do is to generate a template note file based on a run's splits.
I'm a fan of the MIT license.
